apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: self-hosters-by-night
  namespace: flux-system
spec:
  interval: 1h
  url: https://self-hosters-by-night.github.io/helm-charts
